/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/fun`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/home`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container/container`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container/style`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/fun`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/appp/Screens/components/home`; params?: Router.UnknownOutputParams; } | { pathname: `/appp/Screens/components/container/container`; params?: Router.UnknownOutputParams; } | { pathname: `/appp/Screens/components/container`; params?: Router.UnknownOutputParams; } | { pathname: `/appp/Screens/components/container/style`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/fun${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/appp/Screens/components/home${`?${string}` | `#${string}` | ''}` | `/appp/Screens/components/container/container${`?${string}` | `#${string}` | ''}` | `/appp/Screens/components/container${`?${string}` | `#${string}` | ''}` | `/appp/Screens/components/container/style${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/fun`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/home`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container/container`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container`; params?: Router.UnknownInputParams; } | { pathname: `/appp/Screens/components/container/style`; params?: Router.UnknownInputParams; };
    }
  }
}
